[tool.pytest.ini_options]
pythonpath = [
  ".",          # root of repo
  "backend",    # so `backend.models` resolves cleanly
]
testpaths = [
  "backend/tests",
]

[tool.black]
line-length = 88
target-version = ["py313"]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | build
    | dist
    | migrations
  )/
)
'''