
"""baseline postgres schema

Revision ID: 506c4d10e458
Revises: 
Create Date: 2025-09-20 11:37:35.115653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506c4d10e458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('drafting', 'published', 'cancelled', 'completed', name='event_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('entrant1_id', sa.Integer(), nullable=True),
    sa.Column('entrant2_id', sa.Integer(), nullable=True),
    sa.Column('scores', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('entrant1_id IS NULL OR entrant1_id != entrant2_id', name='check_distinct_entrants'),
    sa.ForeignKeyConstraint(['entrant1_id'], ['entrants.id'], ),
    sa.ForeignKeyConstraint(['entrant2_id'], ['entrants.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['entrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('entrants')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
